#!/usr/bin/python


import re
import sys


def main():
    timestamp = re.compile('\[\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}-\d{4}\]')
    days = dict()
    state = 0
    input_file_name = sys.argv[1]
    input_file = open(input_file_name)
    for line in input_file:
        if state == 0:
            if timestamp.match(line):
                day = line[1:11]
            elif line.startswith('SUMMARY:'):
                summary = line[8:]
                state = 1
        elif state == 1:
            if line.strip():
                summary += line
            else:
                if day in days:
                    days[day].append(summary)
                else:
                    days[day] = [summary]
                state = 0
    for day, summaries in sorted(days.iteritems(), reverse=True):
        print '\n*    ' + day + '\n'
        for summary in summaries:
            first = True
            for line in summary.strip().split('\n'):
                if first:
                    first = False
                    print '    *   ' + line
                else:
                    print '        ' + line


if __name__ == '__main__':
    main()

